name: Workflow - sit

on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    if: true
    environment: sit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - id: checkout-code
      uses: actions/checkout@v4

    - id: publish-pypi
      name: Publish PYPI
      uses: ./.github/actions/module-pypi/publish-pypi

    - id: auth-gcp-oidc
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ vars.PROJECT_ID }}
        workload_identity_provider: ${{ vars.SECRET_WIP_NAME }}
        service_account: ${{ vars.PROVIDER_SA_EMAIL }}

    - id: publish-pypi-gcp
      name: Publish PYPI in GCP
      uses: ./.github/actions/gcp-module-pypi/publish-pypi-gcp
      with:
        project_id: ${{ vars.PROJECT_ID }}

  remote-test:
    if: false
    environment: sit
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - id: checkout-code
      uses: actions/checkout@v4
